#!/bin/bash

# To obtain an executable.
ocamlbuild -r\
    -cflags -w,A-4\
    -verbose 0\
    -lib str\
    -lib unix\
    -package graphics\
    -package extlib\
    -tag thread\
    -use-menhir\
    -r\
    Sources/Main.native

mv Main.native calimba


# -cflags -noassert\

# To profile
# ocamlbuild Main.p.native
# Then execute
# Then run gprof ./Main.p.native

